spring:
  application.name: green-cashback

server:
  port: 9094

greenCashbackCalculator:
  url: http://localhost:9095

## https://resilience4j.readme.io/docs/circuitbreaker
resilience4j.circuitbreaker:
  instances:
    cacheBackCalculate:
      registerHealthIndicator: true
      slidingWindowSize: 4
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 3
      waitDurationInOpenState: 23s
      failureRateThreshold: 10
